version: "3.8"

services:
  db:
    container_name: erpi-trucks-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5442:5432"

  pgadmin:
    container_name: erpi-trucks-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@postgres.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    ports:
      - "5443:80"

  adminer:
    container_name: erpi-trucks-adminer
    image: adminer:latest
    restart: always
    ports:
      - "5444:8080"