// <auto-generated />
using System;
using Erpi.Trucks.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erpi.Trucks.Infrastructure.Migrations
{
    [DbContext(typeof(TruckDbContext))]
    [Migration("20240206022620_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erpi.Trucks.Domain.Trucks.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_trucks");

                    b.ToTable("trucks", "public");
                });

            modelBuilder.Entity("Erpi.Trucks.Domain.Trucks.Truck", b =>
                {
                    b.OwnsOne("Erpi.Trucks.Domain.Trucks.AlphanumericCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("code");

                            b1.HasKey("TruckId");

                            b1.ToTable("trucks", "public");

                            b1.WithOwner()
                                .HasForeignKey("TruckId")
                                .HasConstraintName("fk_trucks_trucks_id");
                        });

                    b.OwnsOne("Erpi.Trucks.Domain.Trucks.TruckStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status_code");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status_description");

                            b1.HasKey("TruckId");

                            b1.ToTable("trucks", "public");

                            b1.WithOwner()
                                .HasForeignKey("TruckId")
                                .HasConstraintName("fk_trucks_trucks_id");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
